<?php

namespace AppBundle\Repository;

/**
 * ficheFraisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ficheFraisRepository extends \Doctrine\ORM\EntityRepository
{
}
