<?php

namespace AppBundle\Repository;

/**
 * fraisForfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class fraisForfaitRepository extends \Doctrine\ORM\EntityRepository
{
}
