<?php

namespace AppBundle\Repository;

/**
 * fraisHorsForfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class fraisHorsForfaitRepository extends \Doctrine\ORM\EntityRepository
{
}
