<?php

namespace AppBundle\Repository;

/**
 * listeFraisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class listeFraisRepository extends \Doctrine\ORM\EntityRepository
{
}
